# Generated by Django 3.1 on 2021-11-09 17:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='imagem',
        ),
        migrations.AddField(
            model_name='customusuario',
            name='image',
            field=models.ImageField(blank=True, max_length=50, upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
